/*
 * can_constants.h
 *
 *  Created on: Nov 9, 2024
 *      Author: user
 */

#ifndef INC_CAN_CONSTANTS_H_
#define INC_CAN_CONSTANTS_H_

#include <stdint.h>

// Arbitration Codes
#define RAW_CAN_RESPONSE_ARBITRATION_CODE 0x580
#define RAW_CAN_BOOTLOADER_HEARTBEAT_ARBITRATION_CODE 0x700

// Bootloader Data
#define RAW_CAN_BOOTLOADER_HEARTBEAT_DATA {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
#define RAW_CAN_CANOPEN_HEARTBEAT_PRE_OPERATION_DATA {0x7F}

// Control Word Indices and Values
#define CANOPEN_SDO_INDEX_CONTROL_WORD 0x6040
#define CANOPEN_SDO_SUB_INDEX_CONTROL_WORD 0x00

#define CANOPEN_SDO_INDEX_BRAKE_CONTROL 0x2058
#define CANOPEN_SDO_SUB_INDEX_BRAKE_CONTROL 0x00

// Brake Control Values
#define CANOPEN_SDO_VALUE_BRAKE_CONTROL_BRAKING 0x01
#define CANOPEN_SDO_VALUE_BRAKE_CONTROL_RELEASE 0x03

// Control Word Values
#define CANOPEN_SDO_VALUE_CONTROL_WORD_FAST_DOWN_TIME 0x02
#define CANOPEN_SDO_VALUE_CONTROL_WORD_SERVO_PREPARATION 0x06
#define CANOPEN_SDO_VALUE_CONTROL_WORD_WAIT_SERVO_ENABLE 0x07
#define CANOPEN_SDO_VALUE_CONTROL_WORD_SERVO_RUNNING 0x0F
#define CANOPEN_SDO_VALUE_CONTROL_WORD_CLEAR_EXCEPTION 0x80
#define CANOPEN_SDO_VALUE_CONTROL_WORD_NOT_IMMEDIATELY_UPDATED_SERVO_ENABLED 0x4F
#define CANOPEN_SDO_VALUE_CONTROL_WORD_NOT_IMMEDIATELY_UPDATED_SERVO_START 0x5F
#define CANOPEN_SDO_VALUE_CONTROL_WORD_IMMEDIATELY_UPDATED_SERVO_ENABLED 0x6F
#define CANOPEN_SDO_VALUE_CONTROL_WORD_IMMEDIATELY_UPDATED_SERVO_START 0x7F

// Status Word Indices and Values
#define CANOPEN_SDO_INDEX_STATUS_WORD 0x6041
#define CANOPEN_SDO_SUB_INDEX_STATUS_WORD 0x00

#define CANOPEN_SDO_VALUE_STATUS_WORD_SERVO_READY 0x0001
#define CANOPEN_SDO_VALUE_STATUS_WORD_SERVO_OPERATION_ON 0x0002
#define CANOPEN_SDO_VALUE_STATUS_WORD_SERVO_RUNNING_ENABLED 0x0004
#define CANOPEN_SDO_VALUE_STATUS_WORD_SERVO_FAILURE 0x0008
#define CANOPEN_SDO_VALUE_STATUS_WORD_MAIN_LOOP_CONNECTED 0x0010
#define CANOPEN_SDO_VALUE_STATUS_WORD_FAST_DOWN_TIME 0x0020
#define CANOPEN_SDO_VALUE_STATUS_WORD_WARNING 0x0080
#define CANOPEN_SDO_VALUE_STATUS_WORD_MANUFACTURER_CUSTOM 0x0100
#define CANOPEN_SDO_VALUE_STATUS_WORD_REMOTE_CONTROL 0x0200
#define CANOPEN_SDO_VALUE_STATUS_WORD_TARGET_LOCATION_REACHED 0x0400
#define CANOPEN_SDO_VALUE_STATUS_WORD_NEW_TARGET_LOCATION_RECEIVED 0x1000
#define CANOPEN_SDO_VALUE_STATUS_WORD_ORIGIN_BACK_TO_ZERO_COMPLETED 0x8000

// Mode of Operation
#define CANOPEN_SDO_INDEX_MODE_OF_OPERATION 0x6060
#define CANOPEN_SDO_SUB_INDEX_MODE_OF_OPERATION 0x00

// Mode of Operation Values
#define CANOPEN_SDO_VALUE_MODE_OF_OPERATION_POSITION 0x01
#define CANOPEN_SDO_VALUE_MODE_OF_OPERATION_SPEED 0x03
#define CANOPEN_SDO_VALUE_MODE_OF_OPERATION_ORIGIN 0x06
#define CANOPEN_SDO_VALUE_MODE_OF_OPERATION_INSERT 0x07

// Position Mode Parameters
#define CANOPEN_SDO_INDEX_POSITION_MODE_MAX_SPEED 0x6081
#define CANOPEN_SDO_SUB_INDEX_POSITION_MODE_MAX_SPEED 0x00

#define CANOPEN_SDO_INDEX_POSITION_MODE_ACCELERATION_TIME 0x6083
#define CANOPEN_SDO_SUB_INDEX_POSITION_MODE_ACCELERATION_TIME 0x00

#define CANOPEN_SDO_INDEX_POSITION_MODE_DECELERATION_TIME 0x6084
#define CANOPEN_SDO_SUB_INDEX_POSITION_MODE_DECELERATION_TIME 0x00

#define CANOPEN_SDO_INDEX_POSITION_MODE_TARGET_POSITION 0x607A
#define CANOPEN_SDO_SUB_INDEX_POSITION_MODE_TARGET_POSITION 0x00

// Speed Mode Parameters
#define CANOPEN_SDO_INDEX_SPEED_MODE_ACCELERATION 0x201C
#define CANOPEN_SDO_SUB_INDEX_SPEED_MODE_ACCELERATION 0x00

#define CANOPEN_SDO_INDEX_SPEED_MODE_DECELERATION 0x201D
#define CANOPEN_SDO_SUB_INDEX_SPEED_MODE_DECELERATION 0x00

#define CANOPEN_SDO_INDEX_SPEED_MODE_SPEED 0x60FF
#define CANOPEN_SDO_SUB_INDEX_SPEED_MODE_SPEED 0x00

// Error Codes
#define CANOPEN_SDO_INDEX_ERROR_CODE 0x300A
#define CANOPEN_SDO_SUB_INDEX_ERROR_CODE 0x00

#define CANOPEN_SDO_INDEX_SYSTEM_ERROR_CODE 0x1001
#define CANOPEN_SDO_SUB_INDEX_SYSTEM_ERROR_CODE 0x00

#endif /* INC_CAN_CONSTANTS_H_ */
